package com.seap.smartfinancetracker.transaction.controller;

import com.seap.smartfinancetracker.security.annotation.CurrentUserId;
import com.seap.smartfinancetracker.transaction.dto.RecurringTransactionCreateRequest;
import com.seap.smartfinancetracker.transaction.dto.RecurringTransactionResponse;
import com.seap.smartfinancetracker.transaction.dto.RecurringTransactionUpdateRequest;
import com.seap.smartfinancetracker.transaction.dto.UpcomingRecurringResponse;
import com.seap.smartfinancetracker.transaction.service.RecurringTransactionService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

/**
 * REST Controller for managing automated recurring transactions.
 * <p>
 * This controller exposes endpoints to configure, modify, and monitor scheduled financial
 * activities (e.g., monthly subscriptions, weekly bills, annual incomes). All endpoints
 * strictly enforce data isolation via the {@link CurrentUserId} annotation.
 * </p>
 */
@RestController
@RequestMapping("/recurring-transactions")
@RequiredArgsConstructor
public class RecurringTransactionController {

    private final RecurringTransactionService recurringTransactionService;

    /**
     * Creates a new recurring transaction configuration.
     *
     * @param userId  the authenticated user's ID
     * @param request the payload containing scheduling rules (frequency, amount, category, etc.)
     * @return a {@link ResponseEntity} containing the created {@link RecurringTransactionResponse} and a 201 CREATED status
     */
    @PostMapping
    public ResponseEntity<RecurringTransactionResponse> createRecurringTransaction(
            @CurrentUserId UUID userId,
            @Valid @RequestBody RecurringTransactionCreateRequest request) {
        RecurringTransactionResponse response = recurringTransactionService.createRecurring(userId, request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Retrieves the details of a specific recurring transaction setup.
     *
     * @param userId the authenticated user's ID
     * @param id     the unique identifier of the recurring transaction configuration
     * @return a {@link ResponseEntity} containing the requested {@link RecurringTransactionResponse}
     */
    @GetMapping("/{id}")
    public ResponseEntity<RecurringTransactionResponse> getRecurringTransactionById(
            @CurrentUserId UUID userId,
            @PathVariable UUID id) {
        return ResponseEntity.ok(recurringTransactionService.getRecurringById(userId, id));
    }

    /**
     * Updates an existing recurring transaction configuration.
     *
     * @param userId  the authenticated user's ID
     * @param id      the unique identifier of the recurring transaction to update
     * @param request the payload containing the updated configuration details
     * @return a {@link ResponseEntity} containing the updated {@link RecurringTransactionResponse}
     */
    @PutMapping("/{id}")
    public ResponseEntity<RecurringTransactionResponse> updateRecurringTransaction(
            @CurrentUserId UUID userId,
            @PathVariable UUID id,
            @Valid @RequestBody RecurringTransactionUpdateRequest request
            ) {
        return ResponseEntity.ok(recurringTransactionService.updateRecurring(userId, id, request));
    }

    /**
     * Stops and deletes a recurring transaction configuration.
     * <p>
     * Note: Deleting the recurring configuration does NOT delete the historical
     * transactions that were already generated by this schedule.
     * </p>
     *
     * @param userId the authenticated user's ID
     * @param id     the unique identifier of the recurring transaction to delete
     * @return a {@link ResponseEntity} with a 204 NO CONTENT status upon successful deletion
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRecurring(
            @CurrentUserId UUID userId,
            @PathVariable UUID id) {
        recurringTransactionService.deleteRecurring(userId, id);
        return ResponseEntity.noContent().build();
    }

    /**
     * Toggles the active status of a recurring transaction (Active/inactive).
     * <p>
     * Utilizes a HTTP PATCH method as it performs a partial update to exactly one field
     * (the active flag) without requiring the client to send the entire object payload.
     * </p>
     *
     * @param userId the authenticated user's ID
     * @param id     the unique identifier of the recurring transaction to toggle
     * @return a {@link ResponseEntity} containing the updated {@link RecurringTransactionResponse}
     */
    @PatchMapping("/{id}/toggle")
    public ResponseEntity<RecurringTransactionResponse> toggleActiveStatus(
            @CurrentUserId UUID userId,
            @PathVariable UUID id) {
        return ResponseEntity.ok(recurringTransactionService.toggleActiveStatus(userId, id));
    }

    /**
     * Retrieves a projection of upcoming automated transactions.
     * <p>
     * This endpoint is heavily utilized by frontend dashboards to display cash-flow forecasts
     * and alert users of impending deductions or expected incomes.
     * </p>
     *
     * @param userId the authenticated user's ID
     * @return a {@link ResponseEntity} containing a list of {@link UpcomingRecurringResponse} forecasts
     */
    @GetMapping("/upcoming")
    public ResponseEntity<List<UpcomingRecurringResponse>> getUpcomingTransactions(@CurrentUserId UUID userId) {
        return ResponseEntity.ok(recurringTransactionService.getUpcomingTransactions(userId));
    }
}
